apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: builder-run
spec:
  workspaces:
  - name: shared-data
    subPath: sources-custom-builder
    persistentVolumeClaim:
      claimName: wildfly-pipeline-workspace
  - name: maven-cache
    subPath: maven-repo-cache
    persistentVolumeClaim:
      claimName: wildfly-pipeline-workspace
  pipelineRef:
    name: wildfly-s2i-builder-pipeline
  params:
    - name: builderName
      value: "cloud-server"
    - name: layers
      value: "cloud-server"
