apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wildfly-s2i-builder-pipeline
spec:
  params:
    - name: builderName
      description: "The name of the generated WildFly S2I builder. This name is used to produce the builder ImageStream."
    - name: layers
      description: "The set of Galleon layers to use when provisioning the WildFly server."
    - name: extraFeaturePacks
      default: ""
      description: "Any extra Galleon feature-packs GAV to use in addition to the WildFly Galleon feature-pack."
    - name: wildflyFeaturePack
      default: "org.wildfly:wildfly-galleon-pack"
      description: "GroupId:ArtifactId of the WildFly feature-pack used to provision the WildFly server."
    - name: wildflyCloudFeaturePack
      default: "org.wildfly.cloud:wildfly-cloud-galleon-pack"
      description: "GroupId:ArtifactId of the WildFly Cloud feature-pack used to provision the WildFly server."
    - name: wildflyVersion
      default: "27.0.1.Final"
      description: "WildFly version used to provision the server"
    - name: wildflyCloudVersion
      default: "2.0.0.Final"
      description: "WildFly version used to provision the server"
    - name: namespace
      default: "$(context.pipelineRun.namespace)"
      description: "The namespace where to push the image"
    - name: dockerRegistry
      default: "image-registry.openshift-image-registry.svc:5000"
      description: "The docker Registry URL"
    - name: imageVersion
      default: "latest"
      description: "WildFly s2i builder image version. Can be latest, latest-jdk11 or latest-jdk17"
  workspaces:
    - name: shared-data
    - name: maven-cache
  tasks:
    - name: wildfly-s2i-build-builder
      taskRef:
        name: wildfly-s2i-build-task
      params:
        - name: GALLEON_PROVISION_LAYERS
          value: "$(params.layers)"
        - name: GALLEON_PROVISION_FEATURE_PACKS
          value: "$(params.wildflyFeaturePack):$(params.wildflyVersion),$(params.wildflyCloudFeaturePack):$(params.wildflyCloudVersion),$(params.extraFeaturePacks)"
        - name: builderImageVersion
          value: "$(params.imageVersion)"
        - name: runtimeImageVersion
          value: "$(params.imageVersion)"
        - name: buildBuilder
          value: "true"
      workspaces:
        - name: sources
          workspace: shared-data
        - name: maven-cache
          workspace: maven-cache
    - name: buildah-build-push-builder-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "$(params.dockerRegistry)/$(params.namespace)/$(params.builderName)-builder:$(params.imageVersion)"
        - name: DOCKERFILE
          value: "$(tasks.wildfly-s2i-build-builder.results.builderDockerFile)"
        - name: CONTEXT
          value: "$(tasks.wildfly-s2i-build-builder.results.dockerBuildContext)"
        - name: TLSVERIFY
          value: "false" 
      runAfter: 
        - wildfly-s2i-build-builder
      workspaces:
        - name: source
          workspace: shared-data
    - name: buildah-build-push-runtime-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "$(params.dockerRegistry)/$(params.namespace)/$(params.builderName):$(params.imageVersion)"
        - name: DOCKERFILE
          value: "$(tasks.wildfly-s2i-build-builder.results.dockerFile)"
        - name: CONTEXT
          value: "$(tasks.wildfly-s2i-build-builder.results.dockerBuildContext)"
        - name: TLSVERIFY
          value: "false" 
      runAfter: 
        - wildfly-s2i-build-builder
      workspaces:
        - name: source
          workspace: shared-data
