apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-app
spec:
  workspaces:
  - name: shared-data
    subPath: sources
    persistentVolumeClaim:
      claimName: wildfly-pipeline-workspace
  - name: maven-cache
    subPath: maven-repo-cache
    persistentVolumeClaim:
      claimName: wildfly-pipeline-workspace
  pipelineRef:
    name: wildfly-s2i-build-pipeline
  params:
    - name: gitUrl
      value: "http://github.com/jfdenise/wildfly-s2i-tekton-pipeline"
    - name: revision
      value: openshift
    - name: contextDir
      value: "examples/microprofile"
    - name: imageName
      value: "microprofile-full"
    - name: "deploy"
      value: "true"
