apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: test-app-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push
      kind: ClusterTriggerBinding
    template:
      ref: wildfly-trigger-template
