apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wildfly-s2i-check-builder-task-os
spec:
  params:
   - name: builderName
     type: string
   - name: namespace
     type: string
   - name: failsOnError
     type: string
     default: "false"
  results:
    - name: builderAvailable
      description: true if the builder is available, false otherwise
  steps:
    - name: check-builder
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      script: |
        #!/usr/bin/env sh
        set -eu
        res=$(oc get imagestream $(params.builderName) --namespace $(params.namespace)) || true
          if [ -z "$res" ]; then
            echo "Builder image $(params.builderName) doesn't exist"
            available="false"
            fail="$(params.failsOnError)"
            if  [ "$fail" == "true" ]; then
              exit 1
            fi
          else
            available="true"
            echo "Builder image $(params.builderName) exists"
          fi
          echo -n "$available" > $(results.builderAvailable.path)