apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: main
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-from-listener-run-
    spec:
      pipelineRef:
        name: wildfly-s2i-build-pipeline
      params:
        - name: deploy
          value: "true"
        - name: deployment-name
          value: "test-app"
        - name: gitUrl
          value: "http://github.com/jfdenise/wildfly-s2i"
        - name: revision
          value: "tekton-demo"
        - name: contextDir
          value: "test/test-app"
        - name: outputImage
          value: "registry.minikube/wildfly/sample-test-app-v2"
        - name: kanikoExtraArgs
          value: 
          - --insecure
      workspaces:
      - name: shared-data
        subPath: sources
        persistentVolumeClaim:
          claimName: maven-cache
      - name: maven-cache
        subPath: maven-repo-cache
        persistentVolumeClaim:
          claimName: maven-cache